# quic-tun-server config

server:
    bind-address: ${QUIC_TUN_SERVER_BIND_ADDRESS} # Set to 0.0.0.0 to use all network interfaces, Default to 127.0.0.1
    bind-port: ${QUIC_TUN_SERVER_BIND_PORT} # Default to 7500
    token-parser-plugin: ${QUIC_TUN_SERVER_TOKEN_PARSER_PLUGIN} # Default to Cleartext
    token-parser-key: ${QUIC_TUN_SERVER_TOKEN_PARSER_KEY} # Default to ""
    cert-file: ${QUIC_TUN_SERVER_SECURE_TLS_CERT_KEY_CERT_FILE} # x509 certificate. Default to ""
    key-file: ${QUIC_TUN_SERVER_SECURE_TLS_CERT_KEY_PRIVATE_KEY_FILE} # TLS private key. Default to ""
    verify-client: ${QUIC_TUN_SERVER_VERIFY_CLIENT} # Default to false
    ca-file: ${QUIC_TUN_SERVER_CA_FILE} # Default to ""

restfulapi:
    api-listen-address: ${QUIC_TUN_API_LISTEN_ADDRESS} # Default to 0.0.0.0
    api-listen-port: ${QUIC_TUN_API_LISTEN_PORT} # Default to 8086
